fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "5.2.0"
    apt:
      repo: "git://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "6.3.0"
    download_file:
      repo: "git://github.com/voxpupuli/puppet-download_file"
      ref: "v3.2.0"
    yumrepo_core:
      repo: "https://github.com/puppetlabs/puppetlabs-yumrepo_core.git"
      ref: "1.0.3"
  symlinks:
    newrelic: "#{source_dir}"
